Improve tests workflow with code from Python Agent

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -26,23 +26,44 @@ permissions:
   contents: read
 
 jobs:
+  tests:
+    runs-on: ubuntu-24.04
+    if: always() # Always run, even on cancellation or failure
+    needs:
+      - python
+    steps:
+      - name: Status
+        run: |
+          if [[ "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "Workflow cancelled."
+            exit 1
+          elif [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
+            echo "One or more jobs failed."
+            exit 1
+          else
+            echo "All jobs completed successfully."
+            exit 0
+          fi
+
   # Combine and upload coverage data
   coverage:
-    if: success() || failure() # Does not run on cancelled workflows
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
+    # Don't run this job if triggered by Dependabot, but otherwise run it regardless of success or failure
+    if: ${{ (github.actor != 'dependabot[bot]') && (success() || failure()) }} # Does not run on cancelled workflows
     needs:
       - tests
 
     steps:
-      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
-      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # 6.3.0
+      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
+      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # 7.0.0
         with:
-          python-version: "3.10"
+          python-version: "3.13"
           architecture: x64
 
       - name: Download Coverage Artifacts
         uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # 8.0.1
         with:
+          pattern: coverage-*
           path: ./
 
       - name: Combine Coverage
@@ -59,8 +80,8 @@ jobs:
           fail_ci_if_error: true
           token: ${{ secrets.CODECOV_TOKEN }}
 
-  # Tests
-  tests:
+  # Run Tests
+  python:
     strategy:
       fail-fast: False
       matrix:
@@ -95,14 +116,31 @@ jobs:
           pip install -U wheel setuptools tox
 
       - name: Test
-        run: tox -vv -f ${{ matrix.python.tox-prefix }} -- --cov-report=xml
+        run: |
+          tox run \
+            -v -e ${{ matrix.python.tox-prefix }} \
+            --result-json=./.tox/${{ github.job }}-${{ matrix.python.tox-prefix }}-${{ github.run_id }}-${{ job.check_run_id }}-results.json \
+            --exit-and-dump-after=900
+        env:
+          TOX_PARALLEL_NO_SPINNER: 1
+          FORCE_COLOR: "true"
 
       - name: Upload Coverage Artifacts
-        if: runner.os == 'Linux'
         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
+        if: always()
         with:
           name: coverage-${{ github.job }}-${{ strategy.job-index }}
           path: ./**/.coverage.*
+          include-hidden-files: true
+          if-no-files-found: error
+          retention-days: 1
+
+      - name: Upload Results Artifacts
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
+        if: always()
+        with:
+          name: results-${{ github.job }}-${{ strategy.job-index }}
+          path: ./.tox/*-results.json
           include-hidden-files: true
           if-no-files-found: error
           retention-days: 1
